[package]
name = "financ"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["Zsombor Gegesy <gzsombor@gmail.com>"]

[dependencies]
diesel = { version = "1.3.0", features = ["sqlite"] } 
dotenv = "0.10"
clap = "2.32.0"
chrono = "0.4.5"
calamine = "0.14.1"
