[package]
name = "financ"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["Zsombor Gegesy <gzsombor@gmail.com>"]
description = "Tool to inspect and modify GnuCash files, and correlate with external sources"

[dependencies]
diesel = { version = "1.3.2", features = ["sqlite"] }
dotenv = "0.10"
clap = "2.32.0"
chrono = "0.4.6"
calamine = "0.14.6"
regex = "1"
lazy_static = "1.1.0"
console = "0.6.2"

#[patch.crates-io]
#calamine = { path = "../calamine" }
